In [1]:
import os
import pickle

In [5]:
import pandas as pd
import numpy as np

In [10]:
col = extra_info = ['reg_no', 'int', 'ext', 'total', 'grade','Time', 'Year', 'Type', 'Code', 'Credit', 'Cutoff_S', 'Cutoff_A', 'Cutoff_B', 'Cutoff_C','Cutoff_D','Cutoff_E', 'Dir', 'Absentees', 'Malpractices', 'Detentions', 'NA', 'appeared']
data = pd.read_csv('Data/MainDatabase.csv',sep=',', names=col)
data.head()

C:\Users\Xenon\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning: Columns (0,1,3,9,19) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,reg_no,int,ext,total,grade,Time,Year,Type,Code,Credit,...,Cutoff_B,Cutoff_C,Cutoff_D,Cutoff_E,Dir,Absentees,Malpractices,Detentions,NA,appeared
0,201800001,24.90,9.5,35.00,E,NOV-DEC,2018,NORMAL,MA1101,4.0,...,68.0,57.0,46.0,35.0,NOV-DEC-2018,18,2,14,0.0,512
1,201800022,10.50,1,12.00,F,NOV-DEC,2018,NORMAL,MA1101,4.0,...,68.0,57.0,46.0,35.0,NOV-DEC-2018,18,2,14,0.0,512
2,201800032,11.30,3,15.00,F,NOV-DEC,2018,NORMAL,MA1101,4.0,...,68.0,57.0,46.0,35.0,NOV-DEC-2018,18,2,14,0.0,512
3,201800044,48.50,45.5,94.00,S,NOV-DEC,2018,NORMAL,MA1101,4.0,...,68.0,57.0,46.0,35.0,NOV-DEC-2018,18,2,14,0.0,512
4,201800055,41.50,41.5,83.00,A,NOV-DEC,2018,NORMAL,MA1101,4.0,...,68.0,57.0,46.0,35.0,NOV-DEC-2018,18,2,14,0.0,512

In [11]:
mihir_df = data[data['reg_no'] == '20120148']
mihir_df = mihir_df[['reg_no', 'int', 'ext', 'total', 'grade', 'Credit', 'Code', 'Type', 'Time', 'Year']]
mihir_df

,reg_no,int,ext,total,grade,Credit,Code,Type,Time,Year
119014,20120148,48.00,43.5,92.00,S,4,EE1404,EXTRA,JULY-AUG,2016
119076,20120148,60.00,16,76.00,A,1.5,EE1561_EE507_OLD_,EXTRA,JULY-AUG,2016
119106,20120148,46.40,21.5,68.00,B,4,EE1638,EXTRA,JULY-AUG,2016
119139,20120148,24.00,20,44.00,F,2,EE709,EXTRA,JULY-AUG,2016
119994,20120148,45.70,40,86.00,S,4,IE702_EE705_ELECTIVE_,EXTRA,JULY-AUG,2016
134296,20120148,0.00,DT,0.00,DT,4,EE1404,NORMAL,MAY-JUNE,2016
134887,20120148,0.00,DT,0.00,DT,4,EE1638,NORMAL,MAY-JUNE,2016
135187,20120148,39.00,45,84.00,A,16,EE801,NORMAL,MAY-JUNE,2016
155385,20120148,43.50,47.5,91.00,S,4,EE701,NORMAL,NOV-DEC,2015
155467,20120148,37.80,49,87.00,S,4,EE702,NORMAL,NOV-DEC,2015
155551,20120148,43.00,46.5,90.00,S,4,EE703,NORMAL,NOV-DEC,2015
155632,20120148,43.40,49,93.00,S,4,EE710,NORMAL,NOV-DEC,2015
155712,20120148,0.00,DT,0.00,DT,4,EE705,NORMAL,NOV-DEC,2015
155800,20120148,58.00,18,76.00,B,1.5,EE706,NORMAL,NOV-DEC,2015
155883,20120148,67.00,16,83.00,A,1.5,EE707,NORMAL,NOV-DEC,2015
155966,20120148,24.00,26,50.00,E,2.5,EE708,NORMAL,NOV-DEC,2015
156049,20120148,0.00,DT,0.00,DT,2,EE709,NORMAL,NOV-DEC,2015
180355,20120148,42.70,47.5,91.00,S,4,EE601,NORMAL,MAY-JUNE,2015
180440,20120148,34.85,46.5,82.00,A,4,EE602,NORMAL,MAY-JUNE,2015
180525,20120148,40.40,43,84.00,S,4,EE603,NORMAL,MAY-JUNE,2015
180608,20120148,36.50,37,74.00,B,4,EE605,NORMAL,MAY-JUNE,2015
180695,20120148,38.90,48,87.00,S,4,EE606,NORMAL,MAY-JUNE,2015
180790,20120148,35.05,17,53.00,E,1.5,EE607,NORMAL,MAY-JUNE,2015
180870,20120148,62.00,16,78.00,B,1.5,EE608,NORMAL,MAY-JUNE,2015
180955,20120148,66.25,17,84.00,A,1.5,EE609,NORMAL,MAY-JUNE,2015
181036,20120148,42.50,42.5,85.00,A,2,EE610,NORMAL,MAY-JUNE,2015
181139,20120148,0.00,DT,0.00,DT,4,EE612,NORMAL,MAY-JUNE,2015
201571,20120148,44.25,50,95.00,S,4,EE501,NORMAL,NOV-DEC,2014
201651,20120148,38.40,45.5,84.00,A,4,EE502,NORMAL,NOV-DEC,2014
201741,20120148,35.50,43,79.00,A,4,EE503,NORMAL,NOV-DEC,2014
...,...,...,...,...,...,...,...,...,...,...
253456,20120148,32.50,42,75.00,A,4,EE305,NORMAL,NOV-DEC,2013
253542,20120148,46.00,48.5,95.00,S,4,EE306,NORMAL,NOV-DEC,2013
253628,20120148,51.00,38,89.00,A,1.5,EE307,NORMAL,NOV-DEC,2013
253711,20120148,40.50,23,64.00,D,1.5,EE308,NORMAL,NOV-DEC,2013
270180,20120148,27.10,31.5,59.00,C,4,COA201_COB201,NORMAL,APRIL-MAY-APR,2013
270817,20120148,32.80,38,71.00,A,4,COA202,NORMAL,APRIL-MAY-APR,2013
271141,20120148,34.25,39.25,74.00,A,4,COA203,NORMAL,APRIL-MAY-APR,2013
271478,20120148,34.95,42,77.00,A,4,COA204,NORMAL,APRIL-MAY-APR,2013
271819,20120148,24.75,37,62.00,C,4,COA205,NORMAL,APRIL-MAY-APR,2013
272174,20120148,36.40,39.5,76.00,A,2,COA206,NORMAL,APRIL-MAY-APR,2013
272500,20120148,48.13,34,83.00,A,1.5,COA207,NORMAL,APRIL-MAY-APR,2013
272812,20120148,34.75,33,68.00,C,1.5,COA208,NORMAL,APRIL-MAY-APR,2013
291563,20120148,33.50,34.5,68.00,B,4,COA101_COB101,NORMAL,NOV-DEC,2012
292183,20120148,28.10,30.5,59.00,C,4,COA102,NORMAL,NOV-DEC,2012
292503,20120148,35.13,37,73.00,A,4,COA103,NORMAL,NOV-DEC,2012
292826,20120148,39.60,30.5,71.00,A,4,COA104,NORMAL,NOV-DEC,2012
293142,20120148,33.52,17.5,52.00,D,3,COA105,NORMAL,NOV-DEC,2012
293452,20120148,33.85,33.75,68.00,B,3,COA106,NORMAL,NOV-DEC,2012
293760,20120148,45.38,36,82.00,A,1.5,COA107,NORMAL,NOV-DEC,2012
294071,20120148,46.00,29,75.00,B,1.5,COA108,NORMAL,NOV-DEC,2012
316336,20120148,33.50,34.5,68.00,B,4,COA101_COB101,NORMAL,NOV-DEC,2012
316956,20120148,28.10,30.5,59.00,C,4,COA102,NORMAL,NOV-DEC,2012
317268,20120148,33.50,34.5,68.00,B,4,COA101_COB101,NORMAL,NOV-DEC,2012
317888,20120148,28.10,30.5,59.00,C,4,COA102,NORMAL,NOV-DEC,2012
318208,20120148,35.13,37,73.00,A,4,COA103,NORMAL,NOV-DEC,2012
318531,20120148,39.60,30.5,71.00,A,4,COA104,NORMAL,NOV-DEC,2012
318847,20120148,33.52,17.5,52.00,D,3,COA105,NORMAL,NOV-DEC,2012
319157,20120148,33.85,33.75,68.00,B,3,COA106,NORMAL,NOV-DEC,2012
319465,20120148,45.38,36,82.00,A,1.5,COA107,NORMAL,NOV-DEC,2012
319776,20120148,46.00,29,75.00,B,1.5,COA108,NORMAL,NOV-DEC,2012

In [8]:
info = {'S' : 10, 'A' : 9, 'B' : 8, 'C' : 7, 'D' : 6, 'E' : 5, 'F' : 0, 'DT' : 0, 'I' : 0}
mapped = zip(mihir_df['grade'], mihir_df['Credit'])

In [9]:
sub_sum = 0.0
total_credit = 0.0

for grade, credit in mapped:
    total_credit += float(credit)
    sub_sum += info[grade] * float(credit)
    
gpa = sub_sum/total_credit
gpa

6.198275862068965

In [10]:
for inedex, column in mihir_df.iterrows():
    print(column['reg_no'])
    break

201600045

In [11]:
name = "(my name) is mihir backlog"

'my name' in name

True

In [12]:
lis = [1, 2, 3, 4, 5]
lis[2:6]

[3, 4, 5]

In [41]:
panDict = {'one' : pd.Series(data = [1, 1, 1, 1], index = ['Apple', 'Ball', 'Cat', 'Dog']),
          'two' : pd.Series(data = [1, 1, 1, 1], index = ['Apple', 'Ball', 'Cat', 'Elephant'])}
z = pd.DataFrame(panDict)
z

          one  two
Apple     1.0  1.0
Ball      1.0  1.0
Cat       1.0  1.0
Dog       1.0  NaN
Elephant  NaN  1.0

In [42]:
m = (z.loc['Apple'] == z.loc['Ball'])
m.any()

True

In [1]:
from urllib.request import urlopen as uReq
from bs4 import BeautifulSoup as soup
import re
import pandas as pd
import numpy as np
import os
import pickle

In [92]:
def SaveResults(link):
    # getting html
    #try:
    uClient = uReq(link)
    result_html = uClient.read()
    uClient.close()

    #parsing html
    result_soup = soup(result_html, "html.parser")
    containers = result_soup.find("div", attrs={'style' : 'font-family:courier'})

    # adding content to list
    data = []
    count = 2
    for container in containers:
        if count % 2 == 0:
            data.append(container)
            count += 1
        else:
            count += 1

    # cleaning data
    cleaned_data = []
    count = 0
    for item in data:
        string = item.strip('\r')
        string = string.replace(u'\xa0', u' ')
        string = string.strip('\n')
        string = string.strip('\t')
        string = ' '.join(string.split())
        #print(string)
        cleaned_data.append(string)

    #making data dict
    data_dict = {}
    count = 0
    for item in cleaned_data:
        temp_list = item.replace(' ', ',').split(',')
        new_list = [i.strip(' ') for i in temp_list]
        if new_list != ['']:
            data_dict[count] = new_list
            count += 1
        else:
            pass

    #creating information dict
    subdict = {}
    months = [x.upper() for x in ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December',
     'Jan', 'Feb', 'Mar', 'Apr', 'Nov', 'Dec', 'Aug']]
    years = list(str(x) for x in range(1990, 2050))
    types = ['SUPP', 'EXTRA', 'BACK', 'MAKE']


    for value in data_dict.values():
        if 'GRADE SHEET' in ' '.join(value):

            time_temp = []
            for item in months:
                if item in ' '.join(value).replace('/', ' ').replace('(', ' ').replace(')', ' '):
                    time_temp.append(item)
                else:
                    pass

            if len(time_temp) == 0:
                time_temp.append('EXTRA')

            subdict['Time'] = '-'.join(time_temp)
            subdict['Type'] = None

            for year in years:
                if year in ' '.join(value).replace('/', ' ').replace('(', ' ').replace(')', ' '):
                    subdict['Year'] = year
            
            for item in types:
                if item in ' '.join(value).replace('/', ' ').replace('(', ' ').replace(')', ' '):
                    subdict['Type'] = item

            if subdict['Type'] == None:
                subdict['Type'] = 'NORMAL'

            subdict['Dir'] = '-'.join([subdict['Time'], subdict['Year']])

        elif len(value) >= 2 and value[1] == 'Code':
            subdict_name = value[3].replace('/', '_').replace('(', '_').replace(')', '_').replace('-', '_') + '_dict'
            subdict['Code'] = value[3]

            if subdict['Type'] == 'NORMAL':
                filename = value[3].replace('/', '_').replace('(', '_').replace(')', '_')+'.csv'
            elif subdict['Type'] == 'BACK':
                filename = value[3].replace('/', '_').replace('(', '_').replace(')', '_')+'-Backlog.csv'
            elif subdict['Type'] == 'SUPP':
                filename = value[3].replace('/', '_').replace('(', '_').replace(')', '_')+'-Backlog.csv'
            elif subdict['Type'] == 'MAKE':
                filename = value[3].replace('/', '_').replace('(', '_').replace(')', '_')+'-Backlog.csv'
            elif subdict['Type'] == 'EXTRA':
                filename = value[3].replace('/', '_').replace('(', '_').replace(')', '_')+'-Backlog.csv'
            else:
                pass

        elif len(value) >= 2 and value[1] == 'Title':
            length = len(value)
            temp = []
            for i in range(3, len(value)):
                temp.append(value[i])

            subdict['Title'] = ' '.join(temp)

        elif len(value) >= 4 and value[1] == 'Credit':
            subdict['Credit'] = value[3]

        elif len(value) >= 7 and value[4] == 'E':
            subdict['Cutoff_E'] = value[6]

        elif len(value) >= 7 and value[4] == 'D':
            subdict['Cutoff_D'] = value[6]

        elif len(value) >= 7 and value[4] == 'C':
            subdict['Cutoff_C'] = value[6]

        elif len(value) >= 7 and value[4] == 'B':
            subdict['Cutoff_B'] = value[6]

        elif len(value) >= 7 and value[4] == 'A':
            subdict['Cutoff_A'] = value[6]

        elif len(value) >= 7 and value[4] == 'S':
            subdict['Cutoff_S'] = value[6]

        elif len(value) >= 5 and value[2] == 'Absentees':
            subdict['Absentees'] = value[4]

        elif len(value) >= 5 and value[2] == 'Malpractices':
            subdict['Malpractices'] = value[4]

        elif len(value) >= 5 and value[2] == 'Detentions':
            subdict['Detentions'] = value[4]

        elif len(value) >= 5 and value[2] == 'NA':
            subdict['NA'] = value[4]

        elif len(value) >= 6 and value[3] == 'appeared':
            subdict['appeared'] = value[5]

        elif len(value) >= 10 and 'S' in value[0] and 'A:' in value[2]:
            subdict['Cutoff_S'] = value[0][2:]
            subdict['Cutoff_A'] = value[3][0:2]
            subdict['Cutoff_B'] = value[6][0:2]
            subdict['Cutoff_C'] = value[9][0:2]
            subdict['Cutoff_D'] = value[11][2:4]
            subdict['Cutoff_E'] = value[13][2:4]

        else:
            pass

    for key in subdict:
        subdict[key] = subdict[key].replace('/', '_').replace('(', '_').replace(')', '_')

    info = ['Time', 'Year', 'Dir', 'Type', 'Code', 'Title', 'Credit', 'Cutoff_E', 'Cutoff_S', 'Cutoff_D', 'Cutoff_C', 'Cutoff_B', 'Cutoff_A', 'Absentees', 'Malpractices', 'Detentions', 'NA', 'appeared']

    for item in info:
        if item in subdict.keys():
            pass
        else:
            subdict[item] = 0

    print(subdict)
    exec('{} = {}' .format(subdict_name, subdict))
    #exec('print({})' .format(subdict_name))

    extra_info = [subdict['Time'], subdict['Year'], subdict['Type'], subdict['Code'], subdict['Credit'], subdict['Title'], subdict['Cutoff_S'], subdict['Cutoff_A'], subdict['Cutoff_B'], subdict['Cutoff_C'], subdict['Cutoff_D'], subdict['Cutoff_E'], subdict['Dir'], subdict['Absentees'], subdict['Malpractices'], subdict['Detentions'], subdict['NA'], subdict['appeared']]

    # data cleaning v2.0
    cleaned_dict = {}
    count = 0

    #for key in range(10, len(data_dict) - 14):
    for key in range(len(data_dict)):
        if len(data_dict[key]) >= 5:
            #print(data_dict[key][4])
            if data_dict[key][4].replace('(', ',').split(',')[0] in ['S', 'A', 'B', 'C', 'D', 'E', 'F', 'I', 'P', 'DT', 'MP', 'PASS', 's', 'a', 'b', 'c', 'd', 'e', 'f', 'i', 'p', 'dt', 'na', 'mp', 'pass'] and data_dict[key][0] != 'Lower':
                
                cleaned_dict[count] = data_dict[key][0:5] + extra_info
                count += 1

    #making dataframe
    #print(data_dict)
    df = pd.DataFrame(cleaned_dict).transpose()
    df.columns = ['Reg_No', 'Internal', 'External', 'Total', 'Grade', 'Time', 'Year', 'Type', 'Code', 'Credit', 'Title', 'Cut-Off-S', 'Cut-Off-A', 'Cut-Off-B', 'Cut-Off-C', 'Cut-Off-D', 'Cut-Off-E', 'Directory', 'Absentees', 'Malpractices', 'Detentions', 'NA', 'appeared']


    while(True):
        if os.path.isdir(os.getcwd()+'\\Data-Test\\'+subdict['Dir']):
            df.to_csv(os.getcwd()+'\\Data-Test\\'+subdict['Dir']+'\\'+filename, index = False, encoding='utf-8')
            if subdict['Type'] == 'NORMAL':
                with open(os.getcwd()+'\\Data-Test\\'+subdict['Dir']+'\\'+subdict['Code']+'.pkl', 'wb') as f:
                    exec('pickle.dump({}, f)' .format(subdict_name))
            elif subdict['Type'] == 'BACK-LOG-PAPER':
                with open(os.getcwd()+'\\Data-Test\\'+subdict['Dir']+'\\'+subdict['Code']+'-Backlog.pkl', 'wb') as f:
                    exec('pickle.dump({}, f)' .format(subdict_name))
            else:
                pass

            break

        else:
            try:
                path = os.getcwd()+'\\Data-Test\\'+subdict['Dir']
                os.mkdir(path)

            except:
                print("Error in saving file!")

    while(True):
        rel_path = 'Data-Test\MainDatabase.csv'
        path = os.path.join(os.getcwd(), rel_path)
        if os.path.exists(path):
            with open(path, 'a') as f:
                df.to_csv(f, index=False, header=False)
                f.close()
            break

        else:
            with open(path, "w") as f:
                f.close()

    #print('Completed'+subdict['Code'])
#print("\nResult Saved : "+subdict['Code']+"\t\tType : "+subdict['Type'])

    #except Exception as e:
     #   print(e)
      #  print(link)

In [88]:
def SaveLinks():
    try:
        # get url of result and time
        # eg. 'https://results.smu.edu.in/smit/results_grade_selection.php?exam=41'
        # eg. NOV/DEC-2018

        link = input("Enter Link : ")
        time = input("Enter Time : ")

        # get html data
        pre = 'https://results.smu.edu.in/smit/'
        uClient = uReq(link)
        result_html = uClient.read()
        uClient.close()
        print("Recieved HTML!")

        # parse data
        result_soup = soup(result_html, "html.parser")
        containers = result_soup.findAll("a")
        print("Data Parsed!")

        # save links to a dict
        result_links = dict()
        flag = 0

        for item in result_soup.findAll('a', attrs={'href': re.compile("^results")}):
            result_links[flag] = pre+item.get('href')
            flag += 1
        print("Data saved to dict!")

        if os.path.isdir(os.getcwd()+'\\Data-Test\\'+time):
            with open('.\\Data-Test\\'+time+'\\result_links.pkl', 'wb') as f:
                pickle.dump(result_links, f)
        else:
            try:
                path = os.getcwd()+'\\Data-Test\\'+time
                os.mkdir(path)
                with open('.\\Data-Test\\'+time+'\\result_links.pkl', 'wb') as f:
                    pickle.dump(result_links, f)

            except:
                print("Pickle File Creation Failed!")

        print("File Saved!\n\nStarting Scrapping : \n\n")
        return time

    except Exception as e:
        print("Error in getting links!")

In [20]:
time = SaveLinks()

count = 1
if os.path.exists('./Data-Test/'+time+'/result_links.pkl'):
    links = pickle.load(open('./Data-Test/'+time+'/result_links.pkl', 'rb'))
    total_links = len(links)

    for link in links.values():
        SaveResults(link)
        printProgressBar(count, total_links, prefix = 'Progress:', suffix = 'Complete', length = 50)
        count += 1

Enter Link : dc

KeyboardInterrupt:

In [4]:
# Print iterations progress
def printProgressBar (iteration, total, prefix = '', suffix = '', decimals = 1, length = 100, fill = 'â–ˆ'):
    """
    Call in a loop to create terminal progress bar
    @params:
        iteration   - Required  : current iteration (Int)
        total       - Required  : total iterations (Int)
        prefix      - Optional  : prefix string (Str)
        suffix      - Optional  : suffix string (Str)
        decimals    - Optional  : positive number of decimals in percent complete (Int)
        length      - Optional  : character length of bar (Int)
        fill        - Optional  : bar fill character (Str)
    """
    percent = ("{0:." + str(decimals) + "f}").format(100 * (iteration / float(total)))
    filledLength = int(length * iteration // total)
    bar = fill * filledLength + '-' * (length - filledLength)
    print('\r%s |%s| %s%% %s' % (prefix, bar, percent, suffix), end = '\r')
    # Print New Line on Complete
    if iteration == total:
        print()

In [91]:
SaveResults('https://results.smu.edu.in/smit/results_grade_view.php?exam=8&subject=1604')

{'Time': 'NOV-DEC', 'Type': 'NORMAL', 'Year': '2012', 'Dir': 'NOV-DEC-2012', 'Code': 'MGT-MR-302', 'Title': 'RETAIL DIST. MGT & SUPPLY CHAIN MGT', 'Credit': '4.0', 'Cutoff_E': '45.000000', 'Cutoff_S': '80.000000', 'Cutoff_D': '52.000000', 'Cutoff_C': '59.000000', 'Cutoff_B': '66.000000', 'Cutoff_A': '73.000000', 'Absentees': '0', 'Malpractices': '0', 'Detentions': '2', 'NA': '0', 'appeared': '52'}

In [12]:
CSE501_12__CSE501_7-11__dict = {'Time': 'JULY-AUGUST-AUG', 'Type': 'EXTRA', 'Year': '2015', 'Dir': 'JULY-AUGUST-AUG-2015', 'Code': 'CSE501_12__CSE501_7-11_', 'Title': 'ENGINEERING MATHEMATICS V', 'Credit': '4.0', 'Cutoff_E': '35.000000', 'Cutoff_D': '45.000000', 'Cutoff_C': '56.000000', 'Cutoff_B': '66.000000', 'Cutoff_A': '77.000000', 'Cutoff_S': '87.000000', 'Absentees': 0, 'Malpractices': 0, 'Detentions': 0, 'NA': 0, 'appeared': 0}

In [50]:
lis = [1, 2, 3, 4, 5]
lis[0:6]

[1, 2, 3, 4, 5]

In [68]:
'E'.replace('(', ',').split(',')[0]

'E'

In [ ]:
P